
//====================================================================================================================================================
// Copyright 2023 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================



//==============================================================
// This file is auto generated by FRCrobotCodeGen302.exe Version $CODE_GENERATOR_VERSION$ 
// Changes to this file may cause incorrect behavior and will be lost when 
// the code is regenerated, unless the changes are delimited by:
//  //========= Hand modified code start section x ======== 
//                    Your hand written code goes here
//	//========= Hand modified code end section x ========
//==============================================================


#pragma once

#include <string>
#include <memory>

// FRC Includes
#include <networktables/NetworkTable.h>

class SomeMech
{
    public:
        SomeMech();
        void Initialize();
        void Cyclic();

    private:
        void CheckForTuningEnabled();
        void ReadTuningParamsFromNT();

        double FirstGains_pGain = 0;
double FirstGains_iGain = 0;
double FirstGains_dGain = 0;
double FirstGains_fGain = 0;
double FirstGains_iZone = 0;
double SecondGains_pGain = 0;
double SecondGains_iGain = 0;
double SecondGains_dGain = 0;
double SecondGains_fGain = 0;
double SecondGains_iZone = 0;


        std::string m_ntName = "SomeMech";
        bool m_tuning = false;
        std::shared_ptr<nt::NetworkTable> m_table;
};